spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=Pablo1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
server.servlet.context-path=/api
